### PR TITLE
Feature/flagparse

### PR DESCRIPTION
**Pull request by 200sc**
This makes three significant changes:

1. `ParserCompiler`'s method of evaluating input flags is changed. Previously it would iterate over the input arguments and switch on each of them to linearly check if they matched any known flags. This implementation initializes a `FlagParser` class that can distinguish between known and unknown flags, and parses all flags and inputs only once. In the future, the flag parser could also be told about usage for each flag individually.

2.  Because custom flags are no longer processed in order, but are pre-processed, the signature of `processCustomSwitch` was changed to match the new custom switch set. This changes functionality so that custom switches no longer have the ability to maneuver themselves around the argument list, but have to match either the `-flag value` or boolean `-flag` pattern. This does not break any existing custom switchers, as far as I found.

3. In changing the  signature of `processCustomSwitch`, I recognized that all but one type that used custom switches had identical behavior-- not accepting them. I removed duplicate code in several classes, all of the form of rejecting custom switches, and baked that functionality into the `ZeroSwitcher` abstract class, which implements the new interface `CustomSwitcher`.

There is one other minor functionality change, and that is if you were to pass in multiple flags for the same setting, previously whatever the last flag was would be the one used. In this implementation there is an implicit hierarchy of which flags for each setting are checked and used first, so if you gave `-vv -v -q`, the compiler class would choose -vv, as it is the "safest" choice. I have no attachment to the hierarchies in place, and could also rework this to use the old functionality if it is desired (at the loss of some generality in the FlagParser class).

There are also likely style concerns, I haven't done Java recently but I tried to mimic the style of the project as it exists. I am concerned about the placement of the three new classes in this respect-- I have no attachment to their current packages. 

Following these changes, I tested each individual test in the copper/test directory and all of silver's tests, and everything passed or failed as (what seemed to be, in the case of the copper tests) appropriate.

### CODE REVIEW

**Comment by schwerdf** [comment]
Copper's command-line parser was structured as it was for a specific reason: in a command line such as `java -jar CopperCompiler.jar -customSwitch input.x`, it is impossible to determine syntactically whether `input1.x` is a value belonging to `-customSwitch`, or the name of the first input file.

Since this "flag parser," i.a., purposely excludes the context necessary to resolve this ambiguity properly, it behaves incorrectly in quite a large number of cases. If, for instance, you run it with a boolean switch followed by one input file parameter (_e.g._, `java -jar CopperCompiler.jar -v tests/grammars/Grammar3p23.x`), it crashes. Or if you run it with a boolean switch and more than one input parameter, it ignores the first input parameter.

**Comment by 200sc** [comment]
Apparently the existing tests didn't cover those cases, or I misread the output. The goal of this is just to avoid repeating over the arguments in a large switch. The boolean issue could be resolved by telling the parser which flags expect arguments and which do not, but your first point on custom flags points out why that requires the old signature. I don't have a concern with reverting the signature of `processCustomSwitch`.

**Comment by schwerdf** [comment]
How did you run the tests?

**Comment by 200sc** [comment]
I built every grammar in the tests directory (that did not have a comment saying it was not meant to be built directly) with `ant`.

**Comment by schwerdf** [comment]
That explains the lack of failures; ANT scripts, such as `tests/build.xml` and those generated by Silver, run Copper by means of its ANT task, _bypassing the CLI altogether_.

I fail to understand the overall motivation for these changes. At what point does Copper "[repeat] over the command line arguments in a large switch," and why does this necessitate refactoring the parser on this epic scale?

**Comment by 200sc** [comment]
Ok, well there should probably be tests that test these classes.

The switch in question is [here](https://github.com/melt-umn/copper/blob/develop/src/edu/umn/cs/melt/copper/main/ParserCompiler.java#L263). The motivation for changing it is that the switch is inefficient, verbose, and inextensible. 

If you aren't interested in changing that anyway, I'd still recommend removing the duplicate code for custom switches in each of the parser/compiler/builder implementations and interfaces,

**Comment by schwerdf** [comment]
Ah, so the problem is that it is _not_ a `switch` statement. True, you could do it _slightly_ faster with a hashtable and `switch`, but the current setup is not really an impediment to extensibility, given that (1) the time taken up parsing a short command string is a drop in the bucket next to parsing a Copper spec, not to mention compiling a parser from it, and (2) the CLI is just a thin layer over the Java API, and adding a new built-in switch would involve parallel changes there and in the ANT task, etc., etc.

**Comment by 200sc** [comment]
You don't need a switch, you use a hashtable and check if the table contains the name. It's a change from `N^2` to `N`.

**Comment by 200sc** [comment]
Actually, if switchers had a function that returned their set of possible flags, everything could be done a lot nicer.

**Comment by schwerdf** [comment]
I think you might have misunderstood Copper's status somewhat. It is no longer primarily a research project in its own right. There has been some outside money put toward the goal of making it a tool stable-featured enough to be used in _other people's_ research projects -- through Silver or otherwise.

If you want to learn your way around Copper by hacking on it, I would recommend that you continue doing so in your own clone repository. I am, of course, available to field any questions you might have.

**Comment by 200sc** [comment]
Well, thanks for the suggestion, but I don't think I'll be comfortable working with you. I'll do something else for my master's.

**Pull request closed without merging**
