### PR TITLE
Partial parsers/scanners (fragments) fork

### PR DESCRIPTION
**Pull request by viratyosin**
I intend to move work on my fork `viratyosin/copper` to the new feature branch `fragments` where I will tidy it up for later merging into `develop`

### CODE REVIEW

**Comment by schwerdf** [comment]
These changes appear to modify the parser compilation process substantially, so before any merging happens, I think we should make some runtime comparisons between the `fragments` and `master` branches to verify that compile times have not been significantly impacted.

**Comment by viratyosin** [comment]
I wouldn't say that it modifies the (existing) parser compilation process substantially. Rather, it creates an _alternative_ process. The regular process that silver uses now should run unaffected.

(It may look like a lot of changes since I moved some code around so it could be used twice.)

**Comment by schwerdf** [comment]
I was looking specifically at `LALRLookaheadAndLayoutSetBuilder.java`, with the changes to compute the new `itemLASources` sets, and `LR0DFABuilder.java`, with the changes to compute the new `initNTs` sets. Is this code not being run when the regular process is invoked?

**Comment by viratyosin** [comment]
Ah, yes, you would be correct. I had forgotten about those. I don't expect that particular calculation should have a significant impact, but yes, a runtime comparison would be prudent.

**Comment by viratyosin** [comment]
I did some informal runtime comparisons using `time` and here's what I've got:

Running all of the passing grammar tests individually with cleans in between (3 trials) resulted in about 1% difference in **fragments** favor, (probably just fluctuation).
- **fragments**: 17.542 ms real, 32.977 ms user
- **master**: 17.650 ms real, 33.409 ms user

Processing the XML grammar spec for AbleC generated by Silver (5 trials) resulted in about 1-3% difference in **fragments** favor, (probably just fluctuation)
- **fragments**: 3.165 ms real, 7.364 ms user
- **master**: 3.200 ms real, 7.602 ms user

However, running in "very verbose" mode and reading the times to execute each step in the process resulted in comparable times with the exception of constructing the lookahead sets. Here **fragments** took about 120 ms more time -- which accounts for about a 15% increase in time for that step.

What do you think about these results?

**Comment by schwerdf** [comment]
This looks promising (assuming that all the "ms" figures in the `time` output are actually in units of seconds), but you should also test it on a very large grammar -- Java 1.4 with extensions, `tests/grammars/Java14AllTheFruit.xml`.

**Comment by viratyosin** [comment]
Yes. Good catch, the `time` values are in seconds not milliseconds.

I'll test that Java grammar next.

**Comment by viratyosin** [comment]
Results for running similar tests on `Java14AlltheFruit.xml` yielded similar results with lower overall average runtimes and comparable times for each step in vv mode with the exception of a raised lookahead set computation time.

**Comment by schwerdf** [comment]
Then go ahead and merge the branch into `develop`. When this functionality goes into `master`, we should bump Copper's version number to 0.8.

**Comment by ericvanwyk** [comment]
Kevin,

It doesn't look like this merge has been done.  Can you go ahead and do
that?  Or are you off traveling now?

Cheers,
Eric

**Comment by viratyosin** [comment]
Hi. Sorry so much about that. I am traveling now, but I'll try to do it over the github web face. If it fails I'll let you know.

**Pull request merged**
