### PR TITLE
Allow shiftable set to be accessed from subset disambiguation functions

### PR DESCRIPTION
**Pull request by krame505**
This implements #38 as an experiment so I could test this in Silver.  Don't merge until that issue is worked out.

### CODE REVIEW

**Comment by schwerdf** [comment]
There should be auxiliary methods added to the semantic action container for the disambiguation functions to use when accessing the valid-lookahead-set parameter, so the generaed code will not rely on its being provided specifically as a `BitSet`.

**Comment by schwerdf** [comment]
Substantial effort was put, during the development of Copper 0.7, into making it as easy as possible to swap in new implementations of its components, so that if some unforeseen improvement on the `BitSet` should appear, one does not have to break compatibility with all existing parser specs in order to try it out.

I was thinking of a method that took the `BitSet` and an `int` as parameters, so the code inside the disambiguation function could read, say, `isMember(Identifier_t, shiftable)` instead of using the `BitSet` interface explicitly with `shiftable.get(Identifier_t)`.

**Comment by krame505** [comment]
Ah, that makes sense. 
The way this is currently being interfaced to Silver is by converting the`BitSet` to a Silver list, so then I suppose I would also need to add auxiliary functions to iterate over a `BitSet`?

**Comment by schwerdf** [comment]
Yes. Either that, or generate a line for each disambiguation-function member testing it for membership in `shiftable`.

**Comment by krame505** [comment]
Done, I think this is ready to merge now?  

Also closes #38.

**Pull request merged**
