### PR TITLE
Tests and a tutorial

### PR DESCRIPTION
**Pull request by massimo-zaniboni**
the tests are a little "artificial" because I was testing the conversion from EBNF notation. But some of them are not pasing.

Regarding the tutorial, I created it only for understanding better LALR and Copper. Feel free to not include it, also because I'm not a native English speaker and my style is for sure not in par with the rest of the package. 

Regards,
Massimo

### CODE REVIEW

**Comment by ericvanwyk** [comment]
Thanks, Massimo.  We'll take a look at these.

I'd suggest adding your name in a comment to the top of the new files that
you've submitted, just so we know who wrote them (without having to look in
Git history logs).

Also, should the Tutorial file have a more specific name - perhaps
Tutorial_EBNF_to_BNFN.x ?

-Eric

On Fri, Apr 29, 2016 at 12:31 PM, Massimo Zaniboni <notifications@github.com

**Comment by schwerdf** [comment]
Yes, put copyright headers on. Also, make sure all the tests are working.

For starters, in `TestPrecedences01.x`, you have the precedences the wrong way around. `left_to_right` is assigned a higher precedence than `t_prefix1`, so that when the shift-reduce conflict is resolved, the reduce action is preferred, causing the unexpected results with the two underscores.

A couple of other points:
 1. As this is an interrelated group of tests, they should go in their own subdirectory within `tests/grammars`.
 1. I agree that the tutorial should be given a more specific name.
 1. You should rename the new `RunTestCupGrammar` target to `SelfTestParser`, since its utility is not restricted to grammars specified using the CUP skin, and it assumes that the parser in question has a `main` method, so it cannot be used to run just any.
 1. The HTML grammar dump is a memory-intensive process that, on larger grammars, tends to max out the JVM's resources. If your tests need the dump, it should be turned off by default, with a switch like we have now for the `engine` and `skin` options to turn it on.

**Comment by massimo-zaniboni** [comment]
> Yes, put copyright headers on.

DONE

> Also, make sure all the tests are working.

PENDING: I will check next week. 

> As this is an interrelated group of tests, they should go in their own subdirectory within tests/grammars

DONE
 
> I agree that the tutorial should be given a more specific name.

DONE

> You should rename the new RunTestCupGrammar target to SelfTestParser, since its utility is not restricted to grammars specified using the CUP skin, 

DONE

> If your tests need the dump, it should be turned off by default, with a switch like we have now for the engine and skin options to turn it on.

DONE

**Comment by massimo-zaniboni** [comment]
@schwerdf

> For starters, in TestPrecedences01.x, you have the precedences the wrong way around. 
> left_to_right is assigned a higher precedence than t_prefix1, ... 

Ok! Again 100% my fault! :-) I didn't understood correctly the LALR behavior. I studied better the way conflicts are solved, and now all is making sense. 

> Also, make sure all the tests are working.

DONE: I removed 2 tests that in the light of better knowledge of LALR behavior were simply without any sense.

2 tests are left. They are now passing, after a sanitize process. 

Sincerely, in the end what is left of this pull request is 99.9% my better knowledge of LALR and Copper, and 0.1% some code that is testing very few, and a Tutorial of dubious usefulness...

Feel free to kill all, in case it is doing more arms than good. In any case for me it was a positive experience, because I learnt something! :-)

Regards,
Massimo

**Pull request closed without merging**
